### ISSUE TITLE
distance data problem

### ISSUE THREAD

**Issue by lsenhance** [KitKatFarrelly/LIDAR-Project-Firmware#1]
hello , can you get correct data from epc611 ?  I can get dcs data and use it to calculate distance data , but the distance data is not make sense , did i miss something ? and thanks for your code.

**Comment by KitKatFarrelly** [comment]
heya, sorry about getting back to you so late, been busy with a move. I'm still having issues getting the distance data to be accurate, I'm unsure if it's an issue with the code, or a hardware issue, or an optics issue. I'm planning on running some new tests soon with a crude pinhole camera to see if that improves anything. If I may ask what is the hardware you're using for this, is it a development kit or is it your own board design?

**Comment by KitKatFarrelly** [comment]
Closing this. The formula used in the code to give the actual distance output still needs to be calibrated, but I can confirm that using this code with the sensor board I've posted in https://github.com/KitKatFarrelly/LIDAR-Project-Hardware does result in sensor readings that increase or decrease based on distance from a wall. The main issue for me now is that the distance at which you can get readings like this is very short (less than a foot from my testing) without any sort of optics for the LEDs and light sensor. I will continue to work on improving precision and accuracy of the sensor as I build more tooling for testing and driving the sensor board.
